### ISSUE TITLE
Trying to find source of chii public front_end

### ISSUE THREAD

**Issue by aquaductape** [liriliri/chii#63]
Trying to find source these files (such as host.js) of chii public front_end in the repository.
<img width="320" alt="Screenshot 2024-03-28 at 7 28 13 AM" src="https://github.com/liriliri/chii/assets/29286430/d32f44f4-4b33-4bad-8ad0-0ebadc4835a2">
Tried searching this repo for keywords such as `"enterInspectElementMode"`, which is found in `core/host/host.js` and nothing shows up.
<img width="421" alt="Screenshot 2024-03-28 at 7 29 23 AM" src="https://github.com/liriliri/chii/assets/29286430/c845bb81-b9af-48ab-b55f-9f86876404f9">

**Comment by k-ezis** [comment]
Those files are rendered from depot tools, take a look at the contributing guide: https://github.com/liriliri/chii/blob/master/.github/CONTRIBUTING.md You'll see that you run a command that builds the dev tools front-end from depot tools and outputs it into public/front_end. In order to change those files you'll have to update the underlying front-end code and then re-build.

I'm not a contributor, but hope this helps.
